version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: nestapp/nestapp:1.0.0
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD={password}
    depends_on:
      - db
    networks:
      - nestnet
  db:
    container_name: db
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestnet
volumes:
    pgdata: {}
networks:
  nestnet:
    driver: bridge
